name: Run CBB data R script

on:
  schedule:
    - cron: '0 9 * * *'  
  workflow_dispatch:

jobs:
  run-r-script:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install dependencies
      run: |
        Rscript -e "install.packages(c('DBI', 'RSQLite', 'dplyr', 'data.table', 'stringr', 'rtools', 'curl', 'usethis', 'pkgdown', 'rcmdcheck', 'rversions', 'urlchecker', 'devtools'))"
        Rscript -e "devtools::install_github(repo = 'sportsdataverse/oddsapiR')"

    - name: Run R script
      run: Rscript store_cbb_odds.R  
      env:
        ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }} 
